#!/usr/bin/env bash

CDT=`date +%Y-%m-%d\ %H:%M`  # Current datetime

pelican -o dsmblog content
echo Generated

if [[ $# -eq 0 ]]; then
    DIR=`pwd`"/dsmblog"
    GT="/usr/bin/git --git-dir=${DIR}/.git --work-tree=${DIR} "
    ${GT}add . && ${GT}commit -a -m "Autogenerated: ${CDT}" && ${GT}push
    DIR=`pwd`
    GT="/usr/bin/git --git-dir=${DIR}/.git --work-tree=${DIR} "
    ${GT}add . && ${GT}commit -a -m "Autogenerated: ${CDT}" && ${GT}push
    echo Pushed!
fi
